config/routes.rb
Rails.application.routes.draw do
  resources :words
  root "pages#show", page: "home"

  get "/pages/*page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :users, except: :destroy
  resources :lessons, except: :destroy
  resources :categories, only: [:show, :index]

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :user
  
  has_many :results, dependent: :destroy
  has_many :words, through: :results
  has_many :answers, through: :results

  accepts_nested_attributes_for :results

  validate :validate_word
  
  before_create :random_words
  scope :order_by_id, ->{order id: :desc}

  def answers
    answer_ids = self.results.map{|result| result.answer_id}
    Answer.where id: answer_ids
  end

  private
  def random_words
    self.words = if category.words.size >= Settings.result_size
      category.words.random.limit Settings.result_size
    end
  end

  def validate_word
    if category.words.size < Settings.result_size
      errors[:base] << ""
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user
  before_action :find_lesson, only: [:show, :update]

  def index
    @lessons = Lesson.order_by_id.paginate page: params[:page],
      per_page: Settings.per_page
    @lesson = Lesson.new
    @categories ||= Category.all.collect{|category| [category.name, category.id]}
  end

  def show
    @words = @lesson.category.words
    if @lesson.is_completed?
      @answers = @lesson.answers
    else
      flash[:success] = t "lessons.do_lesson"
    end
  end

  def new
    @lesson = Lesson.new
    @categories ||= Category.all.collect{|category| [category.name, category.id]}
  end

  def create
    @lesson = current_user.lessons.build lesson_params
    if @lesson.save
      flash[:success] = t "lessons.create_success"
      redirect_to lessons_url
    else
      flash[:danger] = t "lessons.create_unsuccess"
      redirect_to lessons_url
    end
  end

  def update
    if @lesson.update_attributes lesson_params.merge is_completed: true
      redirect_to @lesson
      flash[:success] = t "lessons.save"
    else
      flash[:danger] = t "lessons.fail"
      redirect_to :back
    end
  end

  private
  def lesson_params
    params.require(:lesson).permit :user_id, :category_id,
      results_attributes: [:id, :word_id, :answer_id, :_destroy]
  end

  def find_lesson
    @lesson = Lesson.find_by id: params[:id]
    unless @lesson
      flash[:danger] = t "lessons.err"
      redirect_to lessons_url 
    end
  end
end

app/views/lessons/_form.html.erb
<%= form_for @lesson do |f| %>
  <%= f.hidden_field :is_completed, value: true %>
  <%= f.hidden_field :id, value: @lesson.id %>
  <%= f.fields_for :results do |builder| %>
    <div class="form-group">
      <label><%= builder.index + 1 %>. 
        <%= builder.object.word.content %></label>
      <div>
        <div id="answer">
          <% builder.object.word.answers.each do |answer| %>
            <%= builder.radio_button :answer_id, answer.id %>
            <%= answer.content %>
            <%= builder.hidden_field :word_id %>
            <br/>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-md-2">
    <%= f.submit t("lessons.save_lesson"), class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/lessons/_show_result.html.erb
<% @answers.each.with_index 1 do |answer, index| %>
  <p><strong><%= index %>. <%= answer.word.content %></strong></p>
    <% answer.word.answers.each do |_answer| %>
      <div class="radio_inline">
      <ol class="
        list-group-item-<%= _answer.id == answer.id ? "success" : "default" %>">
        <%= radio_button :answer_id, _answer.id, {},
          checked: _answer.id == answer.id, disabled: true %>
        <%= _answer.content %>
      </ol>
      </div>
      <br>
    <% end %>
    <% if answer.is_correct? %>
      <label class="label label-success"><%= t("lessons.correct_a") %></label>
    <% else %>
      <label class="label label-danger"><%= t("lessons.wrong") %></label>
    <% end %>
<% end %>

app/views/lessons/index.html.erb
<% provide :title, t("lessons.list_categories") %>
<div class="container-fluid" id="create">
  <div class="row">
    <%= form_for @lesson do |f| %>
      <%= f.hidden_field :user_id, value: session[:user_id] %>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.select :category_id, @categories, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.submit t("lessons.create_lesson"), class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>
<hr>
<h3 id="exam"><%= t"lessons.list_lesson" %></h3>
<table class="table table-hover">
  <thead>
    <tr class="warning">
      <th><%= t "lessons.create_date" %></th>
      <th><%= t "lessons.name" %></th>
      <th><%= t "lessons.question_number" %></th>
      <th><%= t "lessons.score" %></th>
      <th><%= t "lessons.action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr >
        <td><%= lesson.created_at.to_date() %></td>
        <td><%= lesson.category.name %></td>
        <td><%= lesson.results.count %></td>
        <td>
          <% if lesson.is_completed? %>
            <%= lesson.results.is_corrects.count %>/
            <%= lesson.results.count %>
          <% end %>  
        </td>
        <td id="action" >
          <% if lesson.is_completed? %>
            <%= link_to t("lessons.view"), lesson_path(id: lesson.id),
              method: :get, class: "btn btn-sm btn-info" %>
          <% else %>
            <%= link_to t("lessons.start"), lesson_path(id: lesson.id),
              method: :get, class: "btn btn-sm btn-info" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @lessons %>

app/views/lessons/show.html.erb
<% provide :title, t("lessons.lesson") %>
<div class="row">
  <section>
    <% if @lesson.is_completed? %>
      <h5><%= t "lessons.exam_date" %> <%= @lesson.created_at.to_date() %>
      </h5>
      <h5><%= t "lessons.lesson_score" %><span id="link">
      <%= @lesson.results.is_corrects.count %>/
      <%= @lesson.results.count %></span>
      </h5>
      <h1>
        <%= t "lessons.lesson" %>
        <%= @lesson.id %>
      </h1>
      <hr>
      <%= render "show_result" %>
    <% else %>
      <%= render "form" %>
    <% end %>
  </section>
</div>