config/routes.rb
Rails.application.routes.draw do
  resources :words
  root "pages#show", page: "home"

  get "/pages/*page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :users, except: :destroy
  resources :lessons, except: :destroy
  resources :categories, only: [:show, :index]

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :lessons

  before_save :downcase_email
  attr_accessor :remember_token
  scope :admin, ->{where is_admin: false}

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ?
        BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def current_user? user
    user == current_user   
  end

  def follow other_user
    active_relationships.create following_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :find_user, only: [:destroy, :update, :edit]

  def index
    @users = User.admin.paginate page: params[:page]
  end

  def destroy
    if @user.destroy
      flash[:success] = t "error.destroy_user"
    else
      flash[:danger] = t "error.destroy_err"
    end
    redirect_to admin_users_url
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "error.update_suc"
      redirect_to admin_root_url
    else
      flash[:danger] = t "error.update_er"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:warning] = t "error.user"
      redirect_to admin_users_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :find_user, only: [:update, :edit, :show]
  before_action :correct_user, only: [:edit, :update] 
  
  def new
    @user = User.new
  end

  def index
    @users = User.paginate page: params[:page]
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:info] = t "views.pages.home.welcom_system"
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "error.update_suc"
      redirect_to @user
    else
      flash[:danger] = t "error.update_er"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:warning] = t "error.user"
      redirect_to users_url
    end
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user == @user
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_form_admin.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= render "shared/user_error_messages", object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control", disabled: true  %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/admin.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("admin.title"), admin_admin_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.layouts.header.home"), admin_admin_path %></li>
        <li><%= link_to t("views.layouts.header.user"), "#" %></li>
        <li><%= link_to t("views.layouts.header.categories"), "#" %></li>
        <li><%= link_to t("views.layouts.header.word_list"), "#" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="divider"></li>
            <li>
              <%= link_to t("views.layouts.header.logout"), logout_path, method: :delete  %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/admin/users/edit.html.erb
<% provide :title, t("user.edit_title") %>
<h1><%= t "user.edit_user" %></h1>
<% provide :button_text, t("user.save_change") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form_admin" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">
        <%= t "user.edit" %></a>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("user.title") %>
<h1><% t "user.title" %></h1>
<%= will_paginate %>
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
      <div class="pull-right" style="margin-top: 20px;">
        <%= link_to "Delete", admin_user_path(user), method: :delete,
          class: "btn btn-danger btn-delete",
          data: {confirm: t("admin.delete")} %>
      </div>
    </li>
    <br>
  <% end %>
</ul>