config/routes.rb
Rails.application.routes.draw do
  resources :words
  root "pages#show", page: "home"

  get "/pages/*page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :users, except: :destroy
  resources :lessons, except: :destroy
  resources :categories, only: [:show, :index]

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :words
    end
    resources :words
  end
end

app/views/layouts/_admin.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("admin.title"), admin_root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.layouts.header.home"), admin_root_path %></li>
        <li><%= link_to t("views.layouts.header.user"), admin_users_path %></li>
        <li><%= link_to t("views.layouts.header.categories"),
          admin_categories_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("views.layouts.header.settings"),
              edit_admin_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to t("views.layouts.header.logout"), logout_path,
              method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("views.layouts.footer.about"), "#" %></li>
      <li><%= link_to t("views.layouts.footer.contact"), "#" %></li>
      <li><%= Date.today.year %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("helpers.application_helper.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.layouts.header.home"), "#" %></li>
        <li><%= link_to t("views.layouts.header.help"), "#" %></li>
        <li><%= link_to t("views.layouts.header.linklogin"),
          login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("helpers.application_helper.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.layouts.header.home"), "#" %></li>
        <li><%= link_to t("views.layouts.header.help"), "#" %></li>
        <li><%= link_to t("views.layouts.header.user"), users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("views.layouts.header.profile"),
              user_path(current_user) %></li>
            <li><%= link_to t("views.layouts.header.settings"),
              edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to t("views.layouts.header.logout"),
              logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <% if logged_in? %>
      <%= render current_user.is_admin? ? "layouts/admin" : "layouts/user" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <%= render "layouts/footer" %>
</html>